# Generated by Django 4.1.1 on 2022-09-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
