# Generated by Django 4.1.1 on 2022-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_variation'),
        ('Cart', '0002_rename_cart_id_cartitems_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='variations',
            field=models.ManyToManyField(blank=True, to='Store.variation'),
        ),
    ]
