# Generated by Django 4.1.1 on 2022-10-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='Images/UserProfile/'),
        ),
    ]
